### ISSUE TITLE
Fails when strictures is not installed

### ISSUE THREAD

**Issue by andk** [bluefeet/Games-EveOnline-API#8]
As per subject. Sample fail report: http://www.cpantesters.org/cpan/report/102791172

All reports in a descriptive table: http://analysis.cpantesters.org/reports_by_field?SUBMIT_xxx=Submit&distv=Games-EveOnline-API-0.08&field=qr%3A%28Can%27t+locate+%5CS%2Bpm%29&field=meta%3Adate&field=meta%3Afrom&field=meta%3Aperl&field=qr%3A%28Can%27t+locate+%5CS%2Bpm%29

Thanks,

**Comment by bluefeet** [comment]
This is fixed by adcf04274bbb83a22f5137e063e3d96b7f741e66 in version 0,09.

Thanks for reporting!
